# Generated by Django 6.0.1 on 2026-02-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.CharField(max_length=255, unique=True)),
                ('order_id', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('status_whatsapp', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
