# Generated by Django 6.0.1 on 2026-02-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AddField(
            model_name='order',
            name='event_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
