# Generated by Django 6.0.1 on 2026-02-08 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_product_name_order_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'verbose_name': 'Carrinho Abandonado'},
        ),
    ]
